### ISSUE TITLE
Interior floor

### ISSUE THREAD

**Issue by senhongo** [senhongo/shed#12]
### Tasks
- [x] caulk the seams
- [x] lay plastic covers
- [x] double layer of foam panels
- [x] lay horizontal 2x4 , 4 pieces
- [x] lay vertical 2x4, probably 9 pieces

Separated from #11 as this can't really be worked on until the walls are insulated.

The plan is to have 2 layers of 50mm insulation, followed by 2 layers of 2x4 framing. The top layer will be a single 12mm sheet of plywood. Finally for the finish, we will use simple tiled carpets.

This is a blocker for the final door insulation, let's do this ASAP.

**Comment by senhongo** [comment]
Structure.

- tile carpet
- 12mm ply
- 2x4
- 2x4
- foam
- foam
- plastic cover 
- 24mm base
- frame

**Comment by senhongo** [comment]
Next actions

- [x] trim first of row of 2x4s by 5mm
- [x] measure and cut second row of 2x4s
- [x] check for level with door trim
- [x] lay and trim ply wood

**Comment by senhongo** [comment]
## Progress

- laid the first row of 2x4s and half of the second row
- tested laying the panel on top and it sagged in the middle
- realised there needs to be support in between the rows too, am using off cuts for those
- I'm now out of fresh 2x4s
- there's the material left over from the scaffolding but a lot of them have mold

**Comment by senhongo** [comment]
Could I do the door frame using off cuts of hivest wood and my floor panels?

10mm + 10mm + 12mm = 32mm. The gap is 33mm.

**Comment by senhongo** [comment]
Done.
