### ISSUE TITLE
Driveway deck

### ISSUE THREAD

**Issue by senhongo** [senhongo/shed#21]
## Description

Building a mini-deck around the back door.
Will probably use up our remaining 2x4.

I'd like to make it also be a shelf if we have spare materials. So that I may hang the remaining lumber that's right now just sitting on the floor, soaked in snow melt.

I don't have exact dimensions, but something like 800mm x however long my timber is, 3m?

Height will be low enough for the door to open.

## Objectives
- [ ] able to take off my shoes before entering
- [ ] a little platform so that I can easily move things between garage and kitchen without bending all the way down and to the side.
- [ ] maybe a small set of stairs

## Tasks
- [x] draw up rough plans
- [x] make actual measurements and adjust plans
- [ ] ???
- [x] cut
- [x] assemble
- [x] 🎊

**Comment by senhongo** [comment]
## Dimensions (mm)

Height: 500
Width: between 700 ~ 800
Length: 3000
Step height: 160mm (3 steps)

**Comment by senhongo** [comment]
## Material count

- 3600mm x 8
- 3000mm x 4

**Comment by senhongo** [comment]
Almost done, a few more things to do.

- [ ] add 2 more joists at the 450mm areas for more support, as we're using short planks instead of full length 2x4
- [ ] add remaining surface area

**Comment by senhongo** [comment]
DONE!
