### ISSUE TITLE
Update plans

### ISSUE THREAD

**Issue by senhongo** [senhongo/shed#9]
## Description

Some parts of the plans need updating. Now that the windows and entrances have been finalised, we can finally put in the real dimensions, most importantly using the inner dimensions for the framing.

I would also like to make some changes. Initially the plan was to use a 12FT piece of timber + some off cuts to get to the long side. I've now realised that it's simply to have the short sides extend to the edge, and have the long wall connect to it rather than vice versa.

Also, I want to add an overhang over the windows and entrance way.

## Tasks
- [x] update framing plans
- [x] include windows in framing plans
- [x] add overhang around window and entrance way
